# Generated by Django 4.0.4 on 2022-05-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picamera_img_val', models.TextField()),
                ('ocr_text', models.TextField(default='default')),
                ('weight', models.DecimalField(blank=True, decimal_places='4', max_digits='20')),
                ('score', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
