# Generated by Django 4.0.4 on 2022-05-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkeeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='weight',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
